### PR TITLE
Better locality resolution (part 1)

### PR DESCRIPTION
**Pull request by bcipolli**
This is a partial fix for #191 

Do some basic parsing and normalization on the netfile data:
- Normalize capitalization
- Remove extraneous fields that, empirically, we find to appear.
- Split off middle name from first name.

These are in the `xformnetfilerawdata` command, but any of these could be pushed into model pre-save hooks as well.

See #191 for screen shots on progress.

### CODE REVIEW

**Comment by bcipolli** [comment]
@mikeubell Do you have time to pull this code and try it out? You'd have to clear out your database (it doesn't work retroactively, only on new data).

**Comment by mikeubell** [comment]
I can take a look this afternoon.

**Comment by bcipolli** [comment]
@mikeubell Just updated this with tests, and tweaked the zip code normalization.

**Comment by bcipolli** [comment]
Too many PRs make things challenging to work with, and you start getting merge conflicts and difficult interactions. Lots of things depend on this, is a step in the right direction, and easy enough to back out of.

Merging!

**Pull request merged**
