### PR TITLE
Setting up the back-end API

### PR DESCRIPTION
**Pull request by bcipolli**
So, this turned into much more than moving the stubbed API from the frontend to the backend. Instead, I've changed the API to include new endpoints, based on my own reading of the front-end workflow and feedback from @jnmarcus and @ashajohn.

I tried to follow API practices from here: http://blog.philipphauer.de/restful-api-design-best-practices/

I've also tried to set up tests for most APIs, though at this point I'm unclear about the coverage. Better to get something in with limited coverage, I believe, so that @jnmarcus can start working on the frontend, and @mrmaksimize can work on fleshing out the necessary queries.

### CODE REVIEW

**Comment by bcipolli** [comment]
Non-API changes made along the way:
- Added a `tox.ini` for configuring pep8/pyflakes errors we care (or not) about.
- Moved some properties off of `ballot_item` and onto `referendum`.

**Comment by bcipolli** [comment]
@mrmaksimize do you need anything from me to hop on this?

**Comment by MrMaksimize** [comment]
I think all good for now. Haven't had the time yet - hopefully can look
today.

On Saturday, February 6, 2016, Ben Cipollini notifications@github.com
wrote:

> @mrmaksimize https://github.com/mrmaksimize do you need anything from
> me to hop on this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/caciviclab/disclosure-backend/pull/177#issuecomment-180863863
> .

## 

Sorry for the short message. This was sent from my mobile device.

**Comment by bcipolli** [comment]
@MrMaksimize has been running on this code. This is much better than what exists now; we can iterate over the next RC.

Tentatively merging.

**Pull request merged**
