### PR TITLE
Fix model files self string

### PR DESCRIPTION
**Pull request by rkiddy**
There are problems with the **str** functions in the model files. These are simple fixes.

Sorry, but I cannot figure out how to get the other commit out of this. :-(

### CODE REVIEW

**Comment by tdooner** [comment]
Looks good to me. :+1:

**Comment by adborden** [comment]
@rkiddy are you using python3?

**Comment by adborden** [comment]
FWIW, that format string fix is also valid for the `__unicode__` methods.

**Comment by adborden** [comment]
I just merged this to master.

**Comment by adborden** [comment]
> FWIW, that format string fix is also valid for the **unicode** methods.

Ignore that comment, too much coffee :coffee: :exclamation:

**Comment by rkiddy** [comment]
@adborden I sometimes use python3. For the 2 versions of this project, I have not needed to. It may be worth it to require p3 explicitly.

**Pull request merged**
