### PR TITLE
WIP: add dump_changes command

### LINKED ISSUE #46: Create fixture for ballot app data
Should include the an auth group "Ballot Editors" which can edit all the ballot content. You should be able to dump this from the production db (give it a few weeks).

### PR DESCRIPTION
**Pull request by bcipolli**
The `dump_changes` command reviews the `LogEntry` log of admin interface changes, finds the model changed, and dumps all such models to json.

Fixes #46 (fixture of ballot data). This is useful for creating fixtures of the manual changes that are done in production.

### CODE REVIEW

**Comment by bcipolli** [comment]
I've also marked this as WIP, because there are no tests.

**Comment by bcipolli** [comment]
After making proper tests and watching them fail, I realized (duh!) that this will not work--foreign key constraints will fail. I don't think this makes sense, then--better to just back up the database.

Closing.

**Comment by adborden** [comment]
Interesting. It brings up an important point for our [corrections/annotations feature](https://github.com/caciviclab/disclosure-backend/issues/12), that it needs to reference a unique id from Netfile for it to be useful to other folks.

**Comment by bcipolli** [comment]
> Interesting. It brings up an important point for our corrections/annotations feature, that it needs to reference a unique id from Netfile for it to be useful to other folks.

The report needs to, but the actual database storage does not need to reference a unique ID. For example, if multiple records have the same city misspelling, we can correct it once and have the annotation once. When reporting, we simply use the foreign key pointers to generate the list of relevant Netfile IDs.

**Pull request closed without merging**
