### PR TITLE
Fix failing search test.

### PR DESCRIPTION
**Pull request by mikeubell**

### CODE REVIEW

**Comment by michaelliu2** [comment]
woot!

**Comment by adborden** [comment]
Haha nice, I'll try it out. My instinct was to use San Diego's data, which didn't work. I didn't think to try another city.

**Comment by mikeubell** [comment]
The top level question is where does the test data come from?  The other failing test does not pass using Oakland.

**Comment by adborden** [comment]
@mikeubell I added some work to your branch https://github.com/caciviclab/disclosure-backend/pull/264

To answer your question, the test data comes from Netfile. That's why the tests take so long to run, they're downloading the data from netfile, then loading it into the database. To address that, I've tried to seed the tests with a subset of data from San Diego.

**Pull request merged**
