### PR TITLE
MRG: Better locality resolution (part 2)

### PR DESCRIPTION
**Pull request by bcipolli**
This PR depends on #198 (part 1) and does some magic to enable admin-based entity resolution.

This code:
- Introduces an `aliases` field on `City` and `County` objects, which is a comma-delmited list of aliases and misspellings found for a given city.
- When an admin user adds an alias (e.g. to a `City` model), any `City` model with the added alias as its name gets deleted, and all foreign keys to the deleted model get set to the `City` model with the alias.
- Programmatic managers, so that the `xformnetfilerawcommand` can work with aliases easily as well.
- A command to dump out all non-empty aliases, so they can be reloaded (via a fixture) anywhere.

This is a "work in progress" because tests need to be added. 
Note that this code is non-trivial; @adborden if you have time to review the design, that'd be great. @MrMaksimize there's lots of advanced Django stuff here, but pretty powerful stuff--you may want to take a look!

### CODE REVIEW

**Comment by bcipolli** [comment]
`dump_aliases` should not dump models (lest we fail on foreign key constraints), but rather can be a tsv file with one line per city_name/alias.

**Comment by bcipolli** [comment]
OK, broadened this to:
- Use a csv file to dump/load aliases.
- Store a set of aliases that I've curated (manually)
- Update docs to load those aliases before running `xformnetfilerawdata`
- Add unit tests and tests for dump/load commands.

**Comment by bcipolli** [comment]
@palewire @gordonje Wondering if you two have to deal with city name misspellings in your data. Does this approach make sense to you? Or other approaches you might suggest?

**Comment by bcipolli** [comment]
Once again, code coverage to the rescue (-0.5%) - points out missed tests, and turns out I had a bug in the untested code. Test added, bug fixed! :)

**Comment by adborden** [comment]
@bcipolli I'd be really curious to see what others have done to solve similar problems.

Some weaknesses in the approach:
- You can only have a single "dedupe" field which breaks down as soon as you have non-unique city names (going across states) or if you wanted to de-dupe people in which case you might want to include address fields in addition to names.
- You're losing data integrity because you're deleting records. It might be okay to drop this principle in the short term, but it's important that the finished product has a trail of what changes we made to the data. Other folks have to be able to reproduce our work, otherwise no one can really trust it.

I would suggest considering:
1) keeping the aliases as their own entity with a relationship to the canonical record. Then the duplicates are just linked to the canonical record through the Alias entity.
2) Using a curated list for the localities, that was kind of the idea with importing the ZipCodeMetro data. That way the localities we parse out from netfile would be linked to a known good list. This would also mean having a complete list, even for jurisdictions which aren't included in Netfile.

What do you think?

**Comment by bcipolli** [comment]
> Some weaknesses in the approach:

Thanks for reviewing & pointing out for discussion!

> You can only have a single "dedupe" field

That's true of the current implementation. It would be possible to extend this to take a list of fields, and dynamically append `alias_[fieldname]` fields to the model. I'm not convinced that's a good way to go, but I'm also not convinced it's a bad one.

The positive side is that all the conflict resolution is exposed via the admin interface, and all the magic happens behind the scenes. Also, as long as the `dump_aliases` command is extended as well (not hard), the work is completely repeatable and shareable across implementations.

The negative side is that I've never heard of dynamically pasting on Django fields. Because it'd be done within a decorator, I don't think it would break any apps, but just conceptually, from a developer standpoint, it'd be unusual.

> You're losing data integrity because you're deleting records. 

We've lost data integrity already, by parsing out rows into our own schema, cleaning along the way, and auto-setting foreign keys. So, I don't think this is an extra concern here--I'm deleting records that we set up and own.

> It's important that the finished product has a trail of what changes we made to the data. Other folks have to be able to reproduce our work, otherwise no one can really trust it.

Agreed. The current system is set up with that in mind. Not only is this repeatable, but everything needed to repeat it is stored within our github repo and is part of the installation instructions.

> I would suggest considering:
> 1) keeping the aliases as their own entity with a relationship to the canonical record. Then the >duplicates are just linked to the canonical record through the Alias entity.
> 2) Using a curated list for the localities, that was kind of the idea with importing the ZipCodeMetro data. That way the localities we parse out from netfile would be linked to a known good list. This would also mean having a complete list, even for jurisdictions which aren't included in Netfile.

I think 1) adds unnecessary complexity. We already have to follow a trail to associate a `locality` with a netfile csv row; why not simply use the "canonical record" as the foreign key in our models (which is what I'm essentially doing in this PR)?

I'm not sure the suggestion for 2). Is it that we can use zip codes to auto-correct city name errors within `xformnetfilerawdata`? Or, if something else, can you give me an idea of what user interface (and how to maintain repeatability) you have in mind?

Thanks @adborden ! Glad to work things out--this is a really key decision in the project, getting this right matters :)

**Comment by adborden** [comment]
On Wed, 2016-02-17 at 06:05 -0800, Ben Cipollini notifications@github.com wrote:

> > Some weaknesses in the approach:
> 
> Thanks for reviewing & pointing out for discussion!
> 
> > You can only have a single "dedupe" field
> 
> That's true of the current implementation. It would be possible to extend this to take a list of fields, and dynamically append `alias_[fieldname]` fields to the model. I'm not convinced that's a good way to go, but I'm also not convinced it's a bad one.
> 
> The positive side is that all the conflict resolution is exposed via the admin interface, and all the magic happens behind the scenes. Also, as long as the `dump_aliases` command is extended as well (not hard), the work is completely repeatable and shareable across implementations.

Yeah, I like this part, exposing through the admin interface to manually
clean up the data.

> The negative side is that I've never heard of dynamically pasting on Django fields. Because it'd be done within a decorator, I don't think it would break any apps, but just conceptually, from a developer standpoint, it'd be unusual.

I like the decorator, BTW. But yeah, from a developer standpoint this
approach feels a bit kludgy, both the dynamic fields as well as deleting
records on the fly based on an admin edit. Seems strange that editing a
single record affects multiple other records. Can the user undo this
action if they made a mistake?

FWIW, in my experience it's rare that the intention is to truly delete a
record. In practice I find you usually just want to "tombstone" it or
mark it disabled or inactive. But this kind of gets into the next
part and what it means to "dedupe" localities...

> > You're losing data integrity because you're deleting records. 
> 
> We've lost data integrity already, by parsing out rows into our own schema, cleaning along the way, and auto-setting foreign keys. So, I don't think this is an extra concern here--I'm deleting records that we set up and own.

I disagree here, I would argue that we haven't lost any integrity with
the initial parse, we've only documented it differently (by documenting
it in code). My ideal "corrections" feature would display this as a log
of "edits" we made, starting with a canned one like "remove leading and
trailing whitespace, normalize casing, and other common edits" with a
link to [our methodology
page](https://github.com/caciviclab/disclosure-frontend/issues/22)
explaining some of the other common substitutions made, including a link
to the code for its full gory detail. The rest of the log would include
the manual edits recorded through the admin UI.

But the fact that we disagree on this means we should probably clarify
what the product requirement is in terms of "audit trail". I think we
should continue this conversation and have other folks weigh in on:

https://github.com/caciviclab/disclosure-backend/issues/12
https://github.com/caciviclab/disclosure-backend/issues/17

> > It's important that the finished product has a trail of what changes we made to the data. Other folks have to be able to reproduce our work, otherwise no one can really trust it.
> 
> Agreed. The current system is set up with that in mind. Not only is this repeatable, but everything needed to repeat it is stored within our github repo and is part of the installation instructions.
> 
> > I would suggest considering:
> > 1) keeping the aliases as their own entity with a relationship to the canonical record. Then the >duplicates are just linked to the canonical record through the Alias entity.
> > 2) Using a curated list for the localities, that was kind of the idea with importing the ZipCodeMetro data. That way the localities we parse out from netfile would be linked to a known good list. This would also mean having a complete list, even for jurisdictions which aren't included in Netfile.
> 
> I think 1) adds unnecessary complexity. We already have to follow a trail to associate a `locality` with a netfile csv row; why not simply use the "canonical record" as the foreign key in our models (which is what I'm essentially doing in this PR)?

More complex than the dynamic `alias_` fields and the dedupe command?
IMHO creating a new entity is the more django's style, no?

> I'm not sure the suggestion for 2). Is it that we can use zip codes to auto-correct city name errors within `xformnetfilerawdata`? Or, if something else, can you give me an idea of what user interface (and how to maintain repeatability) you have in mind?

Yeah, this suggestion isn't related to the other comments. I just think
having a canonical curated list solves some problems for us. The main
two are that from a UX perspective, there's a existing list of known
good localities out of box 2) localities outside of what are in netifle
are known.

BTW, have you seen localities outside of CA? Presumably a contribution
could have been made from out of state/country, right?

> Thanks @adborden ! Glad to work things out--this is a really key decision in the project, getting this right matters :)

Sure thing. On that point, most of our changes this far we've gone with
assuming that "it's not a big deal to revert or change the code". But
once we start deleting records, it gets a little trickier. How would you
asses the "riskiness" of this kind of implementation? Would it be hard
move to aliases as an entity for example after living with this change
for a while?

**Comment by bcipolli** [comment]
@adborden Thanks for the comments. I understand more clearly where you're coming from. I have some ideas on how to address things, will think through it more and try to reply later.

As for out-of-state entries: yes, there's tons of out of state (even out of country!) data.

**Comment by bcipolli** [comment]
@adborden Auditability tracking is different than being able to undo changes. The changes in this PR si completely auditable, but the changes are not reversible. How important is reversibility? And to what level?

I think things need to be pretty "magical", to make it work through the admin panel. What I'm thinking is:
- Auto-add a `dedupe_id` field to models using the `DeDupeMixin`. If null, this is a real record. If non-null, this is a dup record. We use managers to hide non-null entries from the admin by default.
- Use the `LogEntry` to track not only edits to `DeDupeMixin`, but also the foreign keys auto-changed.
- If a user changes `DeDupeMixin` when the value is non-null, then:
  1. use old, relevant `LogEntry` records to figure out what foreign keys need to change appropriately.

I think this will allow full tracking through the admin panel. This will also allow users to select, using a dropdown, the duplicate entry.

This also should work for deduping people. Note also that this doesn't prevent us from using the actual `dedupe` tool; this is simply about how to represent these entries in the database, and how to expose the tools to non-techincal users via the admin interface.

I'll see if I can mock this up this morning.

**Comment by bcipolli** [comment]
I have reworked this and have it mostly working. Only issue I see right now is working with how Django does model inheritance. I've dealt with that elsewhere before, so I'll try to fix things up to accommodate. Then I'll probably close this PR and create a new one, the two solutions are non-overlapping.

**Pull request closed without merging**
