### PR TITLE
ENH: add fixture for San Diego reporting periods, 2015 & 2016.

### PR DESCRIPTION
**Pull request by bcipolli**
Here are updated fixtures for getting SD data to run. Similar data should be added for SF/OAK.

This enables:
`python manage.py xformnetfilerawdata --agencies CSD --years 2015,2016`

### CODE REVIEW

**Comment by adborden** [comment]
This is still missing fixtures for reporting periods. I'm creating them locally now. There's usually 2-4 per year depending on jurisdiction and they need to be created for each form, too.

**Comment by adborden** [comment]
Related https://github.com/caciviclab/disclosure-backend/issues/221

**Comment by tdooner** [comment]
I'm going to merge this so we get closer to a backend that works.

In the future, @bcipolli, please pretty-print JSON so it is more readable and easier to diff. My favorite tool for this purpose is `jq`, which you may already know, could help you out like so:

`cat foo.json | jq . | sponge foo.json`

(using `sponge` from the `coreutils` package)

**Comment by KyleW** [comment]
@monkeyhippies - this may be helpful for the issue you're looking at. I believe the fix is to add those missing fixtures @bcipolli mentions.

**Comment by mikeubell** [comment]
python manage.py xformnetfilerawdata --agencies CSD --years 2015,2016
Still fails for me with this merge.  I pulled the develop branch, recreated the db's.  ran makemigrations and then setupserver.  The above command fails with:
Exception: You must add a reporting period for form 'Form 460 Schedule A', locality 'San Diego, CA', containing date 2015-01-15 00:00:00-08:00

**Comment by tdooner** [comment]
@mikeubell you may need to load the fixtures, [according to this](https://docs.djangoproject.com/en/1.8/howto/initial-data/) the command is `python manage.py loaddata`

**Comment by mikeubell** [comment]
That should be documented, particularly what fixture name we are using:
manage.py loaddata: error: No database fixture specified. Please provide the path of at least one fixture in the command line.

**Pull request merged**
