### PR TITLE
Fix netfile download

### PR DESCRIPTION
**Pull request by tdooner**
The column headers in data/netfile/csv/netfile_cal201_transaction.csv
did not match the table schema, resulting in an import error.

I updated the corresponding model to match.

### CODE REVIEW

**Comment by mikeubell** [comment]
I was just about to put in a request containing much of this :-(

**Comment by tdooner** [comment]
Oh, rough :( Sorry for the duplicate work

**Comment by adborden** [comment]
:+1: Looks good, is it possible to make it work better so that _new_ fields from netfile don't break the import?

The assertion message is great so we know exactly what to fix the next time it comes up.

**Comment by tdooner** [comment]
Yeah, I was thinking about that. We could output a warning message, but short of determining the table's schema dynamically (which seems pretty weird), I don't think we're going to be able to automatically do the right thing.

Switch to MongoDB?

**Comment by mikeubell** [comment]
Don't you need to set null=True. I got errors when I did not.

**Pull request merged**
