### PR TITLE
Ballot Item API Response

### PR DESCRIPTION
**Pull request by MrMaksimize**
First attempt at ballot item API response.  Feedback more than welcome, since this is my first Python PR :)

### CODE REVIEW

**Comment by MrMaksimize** [comment]
Hmmm.  Not good.  Need to figure out my build is failing

**Comment by bcipolli** [comment]
@MrMaksimize Ah, didn't see that you opened your PR here! Very cool; see the PR I opened against this branch to resolve the test failures.

**Comment by MrMaksimize** [comment]
Looks like it passes now.  Ready for review

**Comment by bcipolli** [comment]
f'ing awesome. Thanks man! NEXT!

**Pull request merged**
